name: background_location_runner
description: A Flutter plugin for background location tracking on Android and iOS.
version: 1.0.0+1
#publish_to: "https://pub.dev" # For public publishing
homepage: https://github.com/Amarj234/background_location
repository: https://github.com/Amarj234/background_location
author: Amarj234 <amarj234@gmail.com>
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.example.background_location_runner
        pluginClass: BackgroundLocationRunnerPlugin
      ios:
        pluginClass: BackgroundLocationRunnerPlugin

